### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by lorypelli** [PuruVJ/neodrag#168]
![image](https://github.com/user-attachments/assets/b6586133-c20a-4d20-841d-16d93a53a8bc)
it says `Connection Refused`

**Comment by jgabriel98** [comment]
I think this is not related to neodrag.

Could you provide a reproducible example?
and also the `Connection Refused` error stacktrace ?

**Comment by lorypelli** [comment]
> I think this is not related to neodrag.
> 
> Could you provide a reproducible example?
> and also the `Connection Refused` error stacktrace ?

The `blurry text issue` one

**Comment by PuruVJ** [comment]
Thanks a lot for raising this issue! In v3, gpuAcceleration and legacyTranslate will be removed in favor using the `translate: 10px 20px` property, which doesn't have the same mechanism of activating GPU. In fact AFAIK, the gpuAcceleration hack doesn't even work anymore in modern browsers since a year or two easily
