### ISSUE TITLE
Setting position on OnDragEnd has undefined behavior.

### ISSUE THREAD

**Issue by davjhan** [PuruVJ/neodrag#49]
here's an example svelte component:
```
<script>
    import { draggable } from '@neodrag/svelte'

    let x = 100
    let y = 100

    function onDragEnd(e){
        x = 300
        y = 300
    }
</script>
<div
     use:draggable={{
         position: { x, y },
         onDragEnd,
     }}
>
```

Say after I drop it, i want the component to move to (300,300).
On first drag and drop, it works as expected. However, on subsequent ones, the component doesnt snap back to (300,300), it instead stays where it was dropped.

Furthermore, if this was:
```
    function onDragEnd(e){
        x = 0
        y = 0
    }
```

Then it doesnt even move the first time.

**Comment by davjhan** [comment]
Basically, this example is broken:

https://svelte.dev/repl/83d3aa8c5e154b7baf1a9c417c217d2e?version=3.44.1

**Comment by davjhan** [comment]
If I make x and y synced with offsetX and offsetY, it magically works. 
```
    function onDrag(e) {
        x = e.offsetX
        y = e.offsetY
    }
    ```
    
    This should be fixed to be more intuitive.

**Comment by PuruVJ** [comment]
Thanks for bringing this up. I'll investigate it

**Comment by PuruVJ** [comment]
Heya, I fixed the example, it was still listening to on:svelte-drag:end event. Now it works. As for you issue, Im looking at it

**Comment by PuruVJ** [comment]
OK I got the issue. It's the issue when you don't update `x` and `y` on `onDrag` event.

Svelte action can't affect the upstream variable passed to it, so you have to update them manually by listening to onDrag event. In your example, it stays int the same place because x and y are 300 already, and setting them to 300 again won't trigger any .

It's listed here https://github.com/PuruVJ/neodrag/tree/main/packages/svelte#controlled-vs-uncontrolled

![CleanShot 2022-03-18 at 13 12 26@2x](https://user-images.githubusercontent.com/47742487/158957992-716860b8-5994-48b8-bd93-4c7b124db122.png)
